//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eSword.CommentaryEditor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("eSword.CommentaryEditor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] bible {
            get {
                object obj = ResourceManager.GetObject("bible", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1;31;1
        ///2;25;1
        ///3;24;1
        ///4;26;1
        ///5;32;1
        ///6;22;1
        ///7;24;1
        ///8;22;1
        ///9;29;1
        ///10;32;1
        ///11;32;1
        ///12;20;1
        ///13;18;1
        ///14;24;1
        ///15;21;1
        ///16;16;1
        ///17;27;1
        ///18;33;1
        ///19;38;1
        ///20;18;1
        ///21;34;1
        ///22;24;1
        ///23;20;1
        ///24;67;1
        ///25;34;1
        ///26;35;1
        ///27;46;1
        ///28;22;1
        ///29;35;1
        ///30;43;1
        ///31;55;1
        ///32;32;1
        ///33;20;1
        ///34;31;1
        ///35;29;1
        ///36;43;1
        ///37;36;1
        ///38;30;1
        ///39;23;1
        ///40;23;1
        ///41;57;1
        ///42;38;1
        ///43;34;1
        ///44;34;1
        ///45;28;1
        ///46;34;1
        ///47;31;1
        ///48;22;1
        ///49;33;1
        ///50;26;1
        ///1;22;2
        ///2;25;2
        ///3;22;2
        ///4;31;2
        ///5;23;2
        ///6;30;2
        ///7;25;2
        ///8;32;2
        ///9;35;2        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NumberOfVerses {
            get {
                return ResourceManager.GetString("NumberOfVerses", resourceCulture);
            }
        }
    }
}
