//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIB.CommentaryEditor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EIB.CommentaryEditor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1;50;Gen;Genesis;Rdz,Rodz,1 Moj
        ///2;40;Exo;Exodus;Wj,Wyj,2 Moj
        ///3;27;Lev;Leviticus;Kpł,Kap,3 Moj
        ///4;36;Num;Numbers;Lb,4 Moj
        ///5;34;Deu;Deuteronomy;Pwt,5 Moj
        ///6;24;Jos;Joshua;Joz
        ///7;21;Jdg;Judges;Sdz
        ///8;4;Rth;Ruth;Rut,Rt
        ///9;31;1Sa;1 Samuel;1 Sam,1 Sm
        ///10;24;2Sa;2 Samuel;2 Sam,2 Sm
        ///11;22;1Ki;1 Kings;1 Krl,1 Król
        ///12;25;2Ki;2 Kings;2 Krl,2 Król
        ///13;29;1Ch;1 Chronicles;1 Krn,1 Kron
        ///14;36;2Ch;2 Chronicles;2 Krn,2 Kron
        ///15;10;Ezr;Ezra;Ezd
        ///16;13;Neh;Nehemiah;Heh,Ne
        ///17;10;Est;Ester;Est
        ///18;42;Job;Job;Hi,Hiob
        ///19; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Books {
            get {
                return ResourceManager.GetString("Books", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon eib {
            get {
                object obj = ResourceManager.GetObject("eib", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] logo_eib {
            get {
                object obj = ResourceManager.GetObject("logo_eib", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1;31;1
        ///2;25;1
        ///3;24;1
        ///4;26;1
        ///5;32;1
        ///6;22;1
        ///7;24;1
        ///8;22;1
        ///9;29;1
        ///10;32;1
        ///11;32;1
        ///12;20;1
        ///13;18;1
        ///14;24;1
        ///15;21;1
        ///16;16;1
        ///17;27;1
        ///18;33;1
        ///19;38;1
        ///20;18;1
        ///21;34;1
        ///22;24;1
        ///23;20;1
        ///24;67;1
        ///25;34;1
        ///26;35;1
        ///27;46;1
        ///28;22;1
        ///29;35;1
        ///30;43;1
        ///31;55;1
        ///32;32;1
        ///33;20;1
        ///34;31;1
        ///35;29;1
        ///36;43;1
        ///37;36;1
        ///38;30;1
        ///39;23;1
        ///40;23;1
        ///41;57;1
        ///42;38;1
        ///43;34;1
        ///44;34;1
        ///45;28;1
        ///46;34;1
        ///47;31;1
        ///48;22;1
        ///49;33;1
        ///50;26;1
        ///1;22;2
        ///2;25;2
        ///3;22;2
        ///4;31;2
        ///5;23;2
        ///6;30;2
        ///7;25;2
        ///8;32;2
        ///9;35;2        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NumberOfVerses {
            get {
                return ResourceManager.GetString("NumberOfVerses", resourceCulture);
            }
        }
    }
}
