/*=====================================================================================
	Author: (C)2009 - 2020 ITORG Krzysztof Radzimski
	http://itorg.pl
    License: MIT
  ===================================================================================*/

using Usfm.Identifiers.Attributes;

namespace Usfm.Identifiers {
    public enum BookIdentifiers {
        [EnglishName("Genesis")] [Number("01")] OT_GEN,
        [EnglishName("Exodus")] [Number("02")] OT_EXO,
        [EnglishName("Leviticus")] [Number("03")] OT_LEV,
        [EnglishName("Numbers")] [Number("04")] OT_NUM,
        [EnglishName("Deuteronomy")] [Number("05")] OT_DEU,
        [EnglishName("Joshua")] [Number("06")] OT_JOS,
        [EnglishName("Judges")] [Number("07")] OT_JDG,
        [EnglishName("Ruth")] [Number("08")] OT_RUT,
        [EnglishName("1 Samuel")] [Number("09")] OT_1SA,
        [EnglishName("2 Samuel")] [Number("10")] OT_2SA,
        [EnglishName("1 Kings")] [Number("11")] OT_1KI,
        [EnglishName("2 Kings")] [Number("12")] OT_2KI,
        [EnglishName("1 Chronicles")] [Number("13")] OT_1CH,
        [EnglishName("2 Chronicles")] [Number("14")] OT_2CH,
        [EnglishName("Ezra")] [Number("15")] OT_EZR,
        [EnglishName("Nehemiah")] [Number("16")] OT_NEH,
        [EnglishName("Esther (Hebrew)")] [Number("17")] OT_EST,
        [EnglishName("Job")] [Number("18")] OT_JOB,
        [EnglishName("Psalms")] [Number("19")] OT_PSA,
        [EnglishName("Proverbs")] [Number("20")] OT_PRO,
        [EnglishName("Ecclesiastes")] [Number("21")] OT_ECC,
        [EnglishName("Song of Songs")] [Number("22")] OT_SNG,
        [EnglishName("Isaiah")] [Number("23")] OT_ISA,
        [EnglishName("Isaiah")] [Number("24")] OT_JER,
        [EnglishName("Lamentations")] [Number("25")] OT_LAM,
        [EnglishName("Ezekiel")] [Number("26")] OT_EZK,
        [EnglishName("Daniel (Hebrew)")] [Number("27")] OT_DAN,
        [EnglishName("Hosea")] [Number("28")] OT_HOS,
        [EnglishName("Joel")] [Number("29")] OT_JOL,
        [EnglishName("Amos")] [Number("30")] OT_AMO,
        [EnglishName("Obadiah")] [Number("31")] OT_OBA,
        [EnglishName("Jonah")] [Number("32")] OT_JON,
        [EnglishName("Micah")] [Number("33")] OT_MIC,
        [EnglishName("Nahum")] [Number("34")] OT_NAM,
        [EnglishName("Habakkuk")] [Number("35")] OT_HAB,
        [EnglishName("Zephaniah")] [Number("36")] OT_ZEP,
        [EnglishName("Haggai")] [Number("37")] OT_HAG,
        [EnglishName("Zechariah")] [Number("38")] OT_ZEC,
        [EnglishName("Malachi")] [Number("39")] OT_MAL,

        [EnglishName("Matthew")] [Number("41")] NT_MAT,
        [EnglishName("Mark")] [Number("42")] NT_MRK,
        [EnglishName("Luke")] [Number("43")] NT_LUK,
        [EnglishName("John")] [Number("44")] NT_JHN,
        [EnglishName("Acts")] [Number("45")] NT_ACT,
        [EnglishName("Romans")] [Number("46")] NT_ROM,
        [EnglishName("1 Corinthians")] [Number("47")] NT_1CO,
        [EnglishName("2 Corinthians")] [Number("48")] NT_2CO,
        [EnglishName("Galatians")] [Number("49")] NT_GAL,
        [EnglishName("Ephesians")] [Number("50")] NT_EPH,
        [EnglishName("Philippians")] [Number("51")] NT_PHP,
        [EnglishName("Colossians")] [Number("52")] NT_COL,
        [EnglishName("1 Thessalonians")] [Number("53")] NT_1TH,
        [EnglishName("2 Thessalonians")] [Number("54")] NT_2TH,
        [EnglishName("1 Timothy")] [Number("55")] NT_1TI,
        [EnglishName("2 Timothy")] [Number("56")] NT_2TI,
        [EnglishName("Titus")] [Number("57")] NT_TIT,
        [EnglishName("Philemon")] [Number("58")] NT_PHM,
        [EnglishName("Hebrews")] [Number("59")] NT_HEB,
        [EnglishName("James")] [Number("60")] NT_JAS,
        [EnglishName("1 Peter")] [Number("61")] NT_1PE,
        [EnglishName("2 Peter")] [Number("62")] NT_2PE,
        [EnglishName("1 John")] [Number("63")] NT_1JN,
        [EnglishName("2 John")] [Number("64")] NT_2JN,
        [EnglishName("3 John")] [Number("65")] NT_3JN,
        [EnglishName("Jude")] [Number("66")] NT_JUD,
        [EnglishName("Revelation")] [Number("67")] NT_REV,

        [EnglishName("Tobit")] [Number("68")] DC_TOB,
        [EnglishName("Judith")] [Number("69")] DC_JDT,
        [EnglishName("Esther Greek")] [Number("70")] DC_ESG,
        [EnglishName("Wisdom of Solomon")] [Number("71")] DC_WIS,
        [EnglishName("Sirach")] [Number("72")] DC_SIR,
        [EnglishName("Baruch")] [Number("73")] DC_BAR,
        [EnglishName("Letter of Jeremiah")] [Number("74")] DC_LJE,
        [EnglishName("Song of the 3 Young Men")] [Number("75")] DC_S3Y,
        [EnglishName("Susanna")] [Number("76")] DC_SUS,
        [EnglishName("Bel and the Dragon")] [Number("77")] DC_BEL,
        [EnglishName("1 Maccabees")] [Number("78")] DC_1MA,
        [EnglishName("2 Maccabees")] [Number("79")] DC_2MA,
        [EnglishName("3 Maccabees")] [Number("80")] DC_3MA,
        [EnglishName("4 Maccabees")] [Number("81")] DC_4MA,
        [EnglishName("1 Esdras (Greek)")] [Number("82")] DC_1ES,
        [EnglishName("2 Esdras (Latin)")] [Number("83")] DC_2ES,
        [EnglishName("Prayer of Manasseh")] [Number("84")] DC_MAN,
        [EnglishName("Psalm 151")] [Number("85")] DC_PS2,
        [EnglishName("Odae/Odes")] [Number("86")] DC_ODA,
        [EnglishName("Psalms of Solomon")] [Number("87")] DC_PSS,

        [EnglishName("Ezra Apocalypse")] [Number("A4")] DC_EZA,
        [EnglishName("5 Ezra")] [Number("A5")] DC_5EZ,
        [EnglishName("6 Ezra")] [Number("A6")] DC_6EZ,

        [EnglishName("Daniel Greek")] [Number("B2")] DC_DAG,
        [EnglishName("Psalms 152-155")] [Number("B3")] DC_PS3,
        [EnglishName("2 Baruch (Apocalypse)")] [Number("B4")] DC_2BA,
        [EnglishName("Letter of Baruch")] [Number("B5")] DC_LBA,
        [EnglishName("Jubilees")] [Number("B6")] DC_JUB,
        [EnglishName("Enoch")] [Number("B7")] DC_ENO,
        [EnglishName("1 Meqabyan/Mekabis")] [Number("B8")] DC_1MQ,
        [EnglishName("2 Meqabyan/Mekabis")] [Number("B9")] DC_2MQ,

        [EnglishName("3 Meqabyan/Mekabis")] [Number("C0")] DC_3MQ,
        [EnglishName("Reproof")] [Number("C1")] DC_REP,
        [EnglishName("4 Baruch")] [Number("C2")] DC_4BA,
        [EnglishName("Letter to the Laodiceans")] [Number("C3")] DC_LAO
    }
}
