/*=====================================================================================
	Author: (C)2009 - 2020 ITORG Krzysztof Radzimski
	http://itorg.pl
    License: MIT

    https://ubsicap.github.io/usfm/usfm2.5/identification/books.html
  ===================================================================================*/

using System.ComponentModel;
using Usfm.Identifiers.Attributes;

namespace Usfm.Identifiers {
    public enum BookIdentifiers {
        [EnglishName("Genesis")] [Description("‘1 Moses’ in some Bibles")] [Number("01")] OT_GEN,
        [EnglishName("Exodus")] [Description("‘2 Moses’ in some Bibles")] [Number("02")] OT_EXO,
        [EnglishName("Leviticus")] [Description("‘3 Moses’ in some Bibles")] [Number("03")] OT_LEV,
        [EnglishName("Numbers")] [Description("‘4 Moses’ in some Bibles")] [Number("04")] OT_NUM,
        [EnglishName("Deuteronomy")] [Description("‘5 Moses’ in some Bibles")] [Number("05")] OT_DEU,
        [EnglishName("Joshua")] [Description("")] [Number("06")] OT_JOS,
        [EnglishName("Judges")] [Description("")] [Number("07")] OT_JDG,
        [EnglishName("Ruth")] [Description("")] [Number("08")] OT_RUT,
        [EnglishName("1 Samuel")] [Description("1 Kings or Kingdoms in Orthodox Bibles; do not confuse this abbreviation with ISA for Isaiah")] [Number("09")] OT_1SA,
        [EnglishName("2 Samuel")] [Description("2 Kings or Kingdoms in Orthodox Bibles")] [Number("10")] OT_2SA,
        [EnglishName("1 Kings")] [Description("3 Kings or Kingdoms in Orthodox Bibles")] [Number("11")] OT_1KI,
        [EnglishName("2 Kings")] [Description("4 Kings or Kingdoms in Orthodox Bibles")] [Number("12")] OT_2KI,
        [EnglishName("1 Chronicles")] [Description("1 Paralipomenon in Orthodox Bibles")] [Number("13")] OT_1CH,
        [EnglishName("2 Chronicles")] [Description("2 Paralipomenon in Orthodox Bibles")] [Number("14")] OT_2CH,
        [EnglishName("Ezra")] [Description("This is for Hebrew Ezra, sometimes called 1 Ezra or 1 Esdras; also for Ezra - Nehemiah when one book")] [Number("15")] OT_EZR,
        [EnglishName("Nehemiah")] [Description("Sometimes appended to Ezra; called 2 Esdras in the Vulgate")] [Number("16")] OT_NEH,
        [EnglishName("Esther (Hebrew)")] [Description("This is for Hebrew Esther; for the longer Greek LXX Esther use ESG")] [Number("17")] OT_EST,
        [EnglishName("Job")] [Description("")] [Number("18")] OT_JOB,
        [EnglishName("Psalms")] [Description("150 Psalms in Hebrew, 151 Psalms in Orthodox Bibles, 155 Psalms in West Syriac Bibles, if you put Psalm 151 separately in an Apocrypha use PS2, for Psalms 152 - 155 use PS3")] [Number("19")] OT_PSA,
        [EnglishName("Proverbs")] [Description("31 Proverbs, but 24 Proverbs in the Ethiopian Bible")] [Number("20")] OT_PRO,
        [EnglishName("Ecclesiastes")] [Description("Qoholeth in Catholic Bibles; for Ecclesiasticus use SIR")] [Number("21")] OT_ECC,
        [EnglishName("Song of Songs")] [Description("Song of Solomon, or Canticles of Canticles in Catholic Bibles")] [Number("22")] OT_SNG,
        [EnglishName("Isaiah")] [Description("Do not confuse this abbreviation with 1SA for 1 Samuel")] [Number("23")] OT_ISA,
        [EnglishName("Isaiah")] [Description("The Book of Jeremiah; for the Letter of Jeremiah use LJE")] [Number("24")] OT_JER,
        [EnglishName("Lamentations")] [Description("The Lamentations of Jeremiah")] [Number("25")] OT_LAM,
        [EnglishName("Ezekiel")] [Description("")] [Number("26")] OT_EZK,
        [EnglishName("Daniel (Hebrew)")] [Description("This is for Hebrew Daniel; for the longer Greek LXX Daniel use DAG")] [Number("27")] OT_DAN,
        [EnglishName("Hosea")] [Description("")] [Number("28")] OT_HOS,
        [EnglishName("Joel")] [Description("")] [Number("29")] OT_JOL,
        [EnglishName("Amos")] [Description("")] [Number("30")] OT_AMO,
        [EnglishName("Obadiah")] [Description("")] [Number("31")] OT_OBA,
        [EnglishName("Jonah")] [Description("Do not confuse this abbreviation with JHN for John")] [Number("32")] OT_JON,
        [EnglishName("Micah")] [Description("")] [Number("33")] OT_MIC,
        [EnglishName("Nahum")] [Description("")] [Number("34")] OT_NAM,
        [EnglishName("Habakkuk")] [Description("")] [Number("35")] OT_HAB,
        [EnglishName("Zephaniah")] [Description("")] [Number("36")] OT_ZEP,
        [EnglishName("Haggai")] [Description("")] [Number("37")] OT_HAG,
        [EnglishName("Zechariah")] [Description("")] [Number("38")] OT_ZEC,
        [EnglishName("Malachi")] [Description("")] [Number("39")] OT_MAL,

        [EnglishName("Matthew")] [Description("The Gospel according to Matthew")] [Number("41")] NT_MAT,
        [EnglishName("Mark")] [Description("The Gospel according to Mark")] [Number("42")] NT_MRK,
        [EnglishName("Luke")] [Description("The Gospel according to Luke")] [Number("43")] NT_LUK,
        [EnglishName("John")] [Description("The Gospel according to John")] [Number("44")] NT_JHN,
        [EnglishName("Acts")] [Description("The Acts of the Apostles")] [Number("45")] NT_ACT,
        [EnglishName("Romans")] [Description("The Letter of Paul to the Romans")] [Number("46")] NT_ROM,
        [EnglishName("1 Corinthians")] [Description("The First Letter of Paul to the Corinthians")] [Number("47")] NT_1CO,
        [EnglishName("2 Corinthians")] [Description("The Second Letter of Paul to the Corinthians")] [Number("48")] NT_2CO,
        [EnglishName("Galatians")] [Description("The Letter of Paul to the Galatians")] [Number("49")] NT_GAL,
        [EnglishName("Ephesians")] [Description("The Letter of Paul to the Ephesians")] [Number("50")] NT_EPH,
        [EnglishName("Philippians")] [Description("The Letter of Paul to the Philippians")] [Number("51")] NT_PHP,
        [EnglishName("Colossians")] [Description("The Letter of Paul to the Colossians")] [Number("52")] NT_COL,
        [EnglishName("1 Thessalonians")] [Description("The First Letter of Paul to the Thessalonians")] [Number("53")] NT_1TH,
        [EnglishName("2 Thessalonians")] [Description("The Second Letter of Paul to the Thessalonians")] [Number("54")] NT_2TH,
        [EnglishName("1 Timothy")] [Description("The First Letter of Paul to Timothy")] [Number("55")] NT_1TI,
        [EnglishName("2 Timothy")] [Description("The Second Letter of Paul to Timothy")] [Number("56")] NT_2TI,
        [EnglishName("Titus")] [Description("The Letter of Paul to Titus")] [Number("57")] NT_TIT,
        [EnglishName("Philemon")] [Description("The Letter of Paul to Philemon")] [Number("58")] NT_PHM,
        [EnglishName("Hebrews")] [Description("The Letter of Paul to the Hebrews")] [Number("59")] NT_HEB,
        [EnglishName("James")] [Description("The Letter of James")] [Number("60")] NT_JAS,
        [EnglishName("1 Peter")] [Description("The First Letter of Peter")] [Number("61")] NT_1PE,
        [EnglishName("2 Peter")] [Description("The Second Letter of Peter")] [Number("62")] NT_2PE,
        [EnglishName("1 John")] [Description("The First Letter of John")] [Number("63")] NT_1JN,
        [EnglishName("2 John")] [Description("The Second Letter of John")] [Number("64")] NT_2JN,
        [EnglishName("3 John")] [Description("The Third Letter of John")] [Number("65")] NT_3JN,
        [EnglishName("Jude")] [Description("The Letter of Jude; do not confuse this abbreviation with JDG for Judges, or JDT for Judith")] [Number("66")] NT_JUD,
        [EnglishName("Revelation")] [Description("The Revelation to John; called Apocalypse in Catholic Bibles")] [Number("67")] NT_REV,

        [EnglishName("Tobit")] [Description("")] [Number("68")] DC_TOB,
        [EnglishName("Judith")] [Description("")] [Number("69")] DC_JDT,
        [EnglishName("Esther Greek")] [Description("")] [Number("70")] DC_ESG,
        [EnglishName("Wisdom of Solomon")] [Description("")] [Number("71")] DC_WIS,
        [EnglishName("Sirach")] [Description("Ecclesiasticus or Jesus son of Sirach")] [Number("72")] DC_SIR,
        [EnglishName("Baruch")] [Description("5 chapters in Orthodox Bibles (LJE is separate); 6 chapters in Catholic Bibles (includes LJE); called 1 Baruch in Syriac Bibles")] [Number("73")] DC_BAR,
        [EnglishName("Letter of Jeremiah")] [Description("Sometimes included in Baruch; called ‘Rest of Jeremiah’ in Ethiopia")] [Number("74")] DC_LJE,
        [EnglishName("Song of the 3 Young Men")] [Description("	Includes the Prayer of Azariah; sometimes included in Greek Daniel")] [Number("75")] DC_S3Y,
        [EnglishName("Susanna")] [Description("Sometimes included in Greek Daniel")] [Number("76")] DC_SUS,
        [EnglishName("Bel and the Dragon")] [Description("Sometimes included in Greek Daniel; called ‘Rest of Daniel’ in Ethiopia")] [Number("77")] DC_BEL,
        [EnglishName("1 Maccabees")] [Description("Called ‘3 Maccabees’ in some traditions, printed in Catholic and Orthodox Bibles")] [Number("78")] DC_1MA,
        [EnglishName("2 Maccabees")] [Description("Called ‘1 Maccabees’ in some traditions, printed in Catholic and Orthodox Bibles")] [Number("79")] DC_2MA,
        [EnglishName("3 Maccabees")] [Description("Called ‘2 Maccabees’ in some traditions, printed in Orthodox Bibles")] [Number("80")] DC_3MA,
        [EnglishName("4 Maccabees")] [Description("In an appendix to the Greek Bible and in the Georgian Bible")] [Number("81")] DC_4MA,
        [EnglishName("1 Esdras (Greek)")] [Description("The 9 chapter book of Greek Ezra in the LXX, called ‘2 Esdras’ in Russian Bibles, and called ‘3 Esdras’ in the Vulgate; when Ezra - Nehemiah is one book use EZR")] [Number("82")] DC_1ES,
        [EnglishName("2 Esdras (Latin)")] [Description("The 16 chapter book of Latin Esdras called ‘3 Esdras’ in Russian Bibles and called ‘4 Esdras’ in the Vulgate; for the 12 chapter Apocalypse of Ezra use EZA")] [Number("83")] DC_2ES,
        [EnglishName("Prayer of Manasseh")] [Description("Sometimes appended to 2 Chronicles, included in Orthodox Bibles")] [Number("84")] DC_MAN,
        [EnglishName("Psalm 151")] [Description("An additional Psalm in the Septuagint, appended to Psalms in Orthodox Bibles")] [Number("85")] DC_PS2,
        [EnglishName("Odae/Odes")] [Description("A book in some editions of the Septuagint; Odes has different contents in Greek, Russian, and Syriac traditions")] [Number("86")] DC_ODA,
        [EnglishName("Psalms of Solomon")] [Description("A book in some editions of the Septuagint, but not printed in modern Bibles")] [Number("87")] DC_PSS,

        [EnglishName("Ezra Apocalypse")] [Description("12 chapter book of Ezra Apocalypse; called ‘3 Ezra’ in the Armenian Bible, called ‘Ezra Shealtiel’ in the Ethiopian Bible; formerly called 4ES; called ‘2 Esdras’ when it includes 5 Ezra and 6 Ezra")] [Number("A4")] DC_EZA,
        [EnglishName("5 Ezra")] [Description("2 chapter Latin preface to Ezra Apocalypse; formerly called 5ES")] [Number("A5")] DC_5EZ,
        [EnglishName("6 Ezra")] [Description("2 chapter Latin conclusion to Ezra Apocalypse; formerly called 6ES")] [Number("A6")] DC_6EZ,

        [EnglishName("Daniel Greek")] [Description("The 14 chapter version of Daniel from the Septuagint including Greek additions")] [Number("B2")] DC_DAG,
        [EnglishName("Psalms 152-155")] [Description("Additional Psalms 152-155 found in West Syriac manuscripts")] [Number("B3")] DC_PS3,
        [EnglishName("2 Baruch (Apocalypse)")] [Description("The Apocalypse of Baruch in Syriac Bibles")] [Number("B4")] DC_2BA,
        [EnglishName("Letter of Baruch")] [Description("Sometimes appended to 2 Baruch; sometimes separate in Syriac Bibles")] [Number("B5")] DC_LBA,
        [EnglishName("Jubilees")] [Description("Ancient Hebrew book used in the Ethiopian Bible")] [Number("B6")] DC_JUB,
        [EnglishName("Enoch")] [Description("Sometimes called ‘1 Enoch’; ancient Hebrew book in the Ethiopian Bible")] [Number("B7")] DC_ENO,
        [EnglishName("1 Meqabyan/Mekabis")] [Description("Book of Mekabis of Benjamin in the Ethiopian Bible")] [Number("B8")] DC_1MQ,
        [EnglishName("2 Meqabyan/Mekabis")] [Description("Book of Mekabis of Moab in the Ethiopian Bible")] [Number("B9")] DC_2MQ,

        [EnglishName("3 Meqabyan/Mekabis")] [Description("Book of Meqabyan in the Ethiopian Bible")] [Number("C0")] DC_3MQ,
        [EnglishName("Reproof")] [Description("Proverbs part 2: Used in the Ethiopian Bible")] [Number("C1")] DC_REP,
        [EnglishName("4 Baruch")] [Description("Paralipomenon of Jeremiah, called ‘Rest of the Words of Baruch’ in Ethiopia; may include or exclude the Letter of Jeremiah as chapter 1, used in the Ethiopian Bible")] [Number("C2")] DC_4BA,
        [EnglishName("Letter to the Laodiceans")] [Description("A Latin Vulgate book, found in the Vulgate and some medieval Catholic translations")] [Number("C3")] DC_LAO
    }
}
