//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBE.Data.Import.Test.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IBE.Data.Import.Test.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1;Mt 1:23  ;Iz 7:14  
        ///2;Mt 2:6  ;2Sm 5:2  
        ///3;Mt 2:6  ;Mi 5:2  
        ///4;Mt 2:15  ;Oz 11:1  
        ///5;Mt 2:18  ;Jr 31:15  
        ///6;Mt 2:23  ;Sdz 13:5  
        ///7;Mt 2:23  ;Iz 11:1  
        ///8;Mt 3:3  ;Iz 40:3  
        ///9;Mt 3:17  ;Rdz 22:2  
        ///10;Mt 3:17  ;Ps 2:7  
        ///11;Mt 3:17  ;Iz 42:1  
        ///12;Mt 4:4  ;Pwt 8:3  
        ///13;Mt 4:6  ;Ps 91:11  
        ///14;Mt 4:6  ;Ps 91:12  
        ///15;Mt 4:7  ;Pwt 6:16  
        ///16;Mt 4:10  ;Pwt 6:13  
        ///17;Mt 4:15  ;Iz 9:1  
        ///18;Mt 4:16  ;Iz 9:2  
        ///19;Mt 5:5  ;Ps 37:11  
        ///20;Mt 5:21  ;Wj 20:13  
        ///21;Mt 5:21  ;Pwt 5:17  
        ///22;Mt 5:27  ;Wj 20: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Cytaty_z_G_w_NT {
            get {
                return ResourceManager.GetString("Cytaty_z_G_w_NT", resourceCulture);
            }
        }
    }
}
